name: system_info2
version: 2.0.1
homepage: https://github.com/bsutton/system_info
description: Provides easy access to useful information about the system (architecture, bitness, kernel, memory, operating system, CPU, user).
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  file_utils: ^1.0.0
  path: ^1.8.0
dev_dependencies: 
  lint_hard: ^1.0.4
  pedantic: ^1.10.0
